### ISSUE TITLE
Investigate if we should send an initial message on negotiationMandatory = false

### ISSUE THREAD

**Issue by mkozjak** [mkozjak/node-telnet-client#49]

**Comment by mkozjak** [comment]
#46

**Comment by callahanp** [comment]
In my case there is no login, and the node-telnet-client connection just times out instead of becoming ready.
The connection works using the telnet command. The telnet server opens the connection and just sits there waiting for a command without displaying a prompt in the terminal.
In the terminal you see: 
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

Although the tcp connection is made, and can be used from the terminal, no prompt appears until after the first command.

'use strict';
/* eslint-env es6 */
let Telnet = require('telnet-client');
let connection;
function connectToFlightgear(){
  connection = new Telnet();
  let params = {
    host: '127.0.0.1',
    port: 5400,
    shellPrompt: '/>',
    timeout: 5000,
    sendTimeout: 5000,
    negotiationMandatory: false,
    debug:true,
    // removeEcho: 4
  };

  connection.on('ready', function(prompt) {
    connection.exec(cmd, function(err, response) {
      console.log(response);
    });
  });

  connection.on('timeout', function() {
    console.log('socket timeout!');
    connection.end();
  });

  connection.on('close', function() {
    console.log('connection closed');
  });
  connection.connect(params);
}
module.exports = {connectToFlightgear};

**Comment by mkozjak** [comment]
@callahanp Fixed in 0.15.0! ```initialLFCR``` parameter must be set on connection!
