### ISSUE TITLE
Generator error handling

### ISSUE THREAD

**Issue by Starfox64** [mkozjak/node-telnet-client#62]
As far as I understand, the current correct way to handle connection errors is this:

```javascript
co(function*() {
	const telnetConnection = new telnet();

	telnetConnection.on('error', (e) => {
		//Handle Error
	});

	yield telnetConnection.connect({
		host: '127.0.0.1',
		port: 23
	});
})
```

I believe it would be better like this:

```javascript
co(function*() {
	const telnetConnection = new telnet();

	try {
		yield telnetConnection.connect({
			host: '127.0.0.1',
			port: 23
		});
	} catch (e) {
		//Handle error
	}
})
```

**Comment by mkozjak** [comment]
@Starfox64: I agree completely! The problem is in the design where the lib was originally made for callbacks only. Later the promises were added. I cannot reject here easily. A rewrite with babel is planned to aid this issue.

https://github.com/mkozjak/node-telnet-client/issues/57

Sorry for the inconvenience.

**Comment by mkozjak** [comment]
This is not really possible, since we're trying to support both callbacks and promises in the same call.
```net.createConnection``` doesn't throw when the error occurs, so we must rely on an ```error``` event. We would somehow need to both emit an error and reject that same error so we can support both interfaces and that's nasty.
